### ISSUE TITLE
Right click sporadically stops working

### ISSUE THREAD

**Issue by alexolog** [M-Reimer/undoclosetab#123] opened 2023-05-01 03:29 UTC
Every now and then, right-clicking on the addon icon stops showing the closed tabs.  Sometimes it still works in other windows, but it seems that it picks tabs from the wrong window.

For example, if I have windows A, B, C, and D open, with many tabs in each, at some point right-clicking on the icon will not show any closed tabs in windows A, B, and C, but in window D, it will show tabs that were closed in window A, or some similar discrepancy.

The log says `TypeError: can't access property "replace", tab.title is undefined` in this function:
```
// Helper function used to create menu entries based on tab properties
function TabMenuProperties(tab, id_prefix) {
  return {
    id: id_prefix + ":" + tab.sessionId,
    title: tab.title.replace(/&/g, "&&"),
    icons: {18: tab.favIconUrl || "icons/no-favicon.svg"}
  }
}
```

**Comment by M-Reimer** [comment] 2023-05-04 05:37
This is a duplicate of #117 
But thanks for tracking it down to the relevant code line.
I hope I'll find time to create a "workaround release" this weekend.

**Closed by M-Reimer** 2023-05-04 05:37 UTC
