### ISSUE TITLE
Tabs can only be restored for up to the last session

### ISSUE THREAD

**Issue by NiGHTsC** [M-Reimer/undoclosetab#79] opened 2020-09-29 04:50 UTC
Hi,
Is it still do-able?

Thank you.

**Comment by M-Reimer** [comment] 2020-09-29 04:59
From the last: Yes. But currently not from any session prior the last.

**Comment by NiGHTsC** [comment] 2020-09-29 05:08
From the last is good enough, any chance we can have this feature in the future?

**Comment by M-Reimer** [comment] 2020-09-29 06:17
Depends on Mozilla fixing https://bugzilla.mozilla.org/show_bug.cgi?id=1538119

Currently I have to use a workaround which makes it difficult to restore tabs from previous sessions. But it is better to be limited in restores from previous sessions compared to restoring random tabs and windows.

**Comment by NiGHTsC** [comment] 2020-09-29 06:34
Well well well...another API fix on the list :(
Let's hope for the best then!

Thanx again!

**Comment by M-Reimer** [comment] 2020-09-29 18:29
Will keep this one as tracking bug. If Mozilla ever fixes the linked bug, it would be possible to remove the workaround that is currently needed to restore tabs without randomly restoring unwanted tabs or windows.

**Comment by Gitoffthelawn** [comment] 2023-12-18 11:32
Just FYI, Bugzilla's BugBot was proposing possibly closing that bug as `INCOMPLETE`.  Has BugBot been satisfied, or does it need to be fed so that bug doesn't get closed?

**Comment by M-Reimer** [comment] 2023-12-19 10:51
For me it seems like the bot proposes "INCOMPLETE" but will not set this automatically.

But either way I don't think this will be fixed in the near future. Seems like Add-on API is lowest priority for Mozilla.

**Comment by Gitoffthelawn** [comment] 2023-12-19 10:55
Yes, I find BugBot's explanations to be lacking and unclear.  Hopefully you are correct with your interpretation.

Yes, the add-on API seems to be a lower priority for Mozilla.  Probably not the lowest, but definitely lower than you or I would prefer!

**Comment by M-Reimer** [comment] 2023-12-19 11:09
I had a short view at the relevant code, myself, and it is lacking comments, which makes it difficult to find a way into.

**Comment by Gitoffthelawn** [comment] 2023-12-20 04:47
Firefox's code? Yep.  It's a nearly comment-less jungle.  I've never see "professional" code with so few comments and so little documentation.  I feel sadness every time I read it.  Sad that anyone found it acceptable to publish code in that manner. Additional sadness that they chose to do so for such a critical and important project.

**Comment by M-Reimer** [comment] 2023-12-21 15:16
https://bugzilla.mozilla.org/show_bug.cgi?id=1789652
https://bugzilla.mozilla.org/show_bug.cgi?id=1845836

Just two more bugs around this issue. Both are fixed and the fixes of the two seem to have fixed our bug "by accident", too. Probably I don't even want to know how many bugs Mozilla has in their BugZilla without knowing that they have been accidentally fixed. Will take me a bit more time to debug and pinpoint which Firefox release has the fix for the first time, but probably the workaround for this bug can go.

In this process I'll now also remove Android support. With Mozilla adding the forced "Add-ons" menu level, they basically made it useless to use an Add-on for restoring tabs. Going over "History" is the same amount of "taps".

**Comment by M-Reimer** [comment] 2023-12-21 18:39
I was no longer able to reproduce the issue, so hopefully it's gone.

Just for the record: It needed the bug to **`appear somewhere else`** for it to get fixed. The Add-ons API bug is still open and nobody cared about the problem as long as it "only was an Add-on problem".

**Closed by M-Reimer** 2023-12-21 18:39 UTC
Labels: upstream bug

**Comment by Gitoffthelawn** [comment] 2023-12-22 05:14
> ...Will take me a bit more time to debug and pinpoint which Firefox release has the fix for the first time, but probably the workaround for this bug can go.

Don't forget that ESR is on v115.  So probably changes made before Firefox v115 are widely adopted by now.

**Comment by M-Reimer** [comment] 2023-12-22 15:13
> Don't forget that ESR is on v115. So probably changes made before Firefox v115 are widely adopted by now.

That's why I deleted my workaround completely. Finally getting rid of this workaround probably fixed a few other issues, too. Still have to check some of them.

**Comment by Gitoffthelawn** [comment] 2023-12-24 05:26
Sounds good.  BTW, in rereading my last post, I'm not sure if I chose the best words.  What I was trying to convey is that you can likely assume most people have Firefox v115 or later, but it's best not to assume that anyone has anything newer than v115, since that's the current ESR.  That's more words, but probably more clear. ;)
