### ISSUE TITLE
Left Click does not Reopen Tabs; Right Click shows no Tabs to Reopen

### ISSUE THREAD

**Issue by GTHub23** [M-Reimer/undoclosetab#89] opened 2021-02-12 14:06 UTC
I'm sure this has happened before on odd occasions and may well be something that can't be fixed, but I'll let you know here to at least make you aware

**Situation**
Just closed a tab and wish to reopen it in Firefox (v85.0.2) on Windows 7

_Steps_
1. Left click "Undo Closed Tabs" button on toolbar
2. Alternatively: Right click "Undo Closed Tabs" button on toolbar

_What Should Happen_
1. Left clicking should immediately reopen the most recently closed tab(s)
2. Right clicking should display a list of recent closed tabs and clicking on the desired tab should reopen it

_What Actually Happens_
1. Left clicking does not reopen the most recently closed tab(s)
2. Right clicking displays the default menu options from the browser; no closed tabs are displayed

_How To Fix_
I have found a way to fix this issue myself. Disabling/reinstalling the addon has no effect however:
1. Go to "about:config"
2. Change "browser.sessionstore.max_tabs_undo" and browser.sessionstore.max_windows_undo" to "0"
3. Restart Firefox (may be optional; haven't tested)
4. Reset "browser.sessionstore.max_tabs_undo" and browser.sessionstore.max_windows_undo" to "25" and "3" respectively

Doing the above steps seems to fix the issue, so I'm not sure if this is a Firefox or an addon related issue. I've checked all my other addons and this seems to be the only one affected, and my profile has not been corrupted; at least as far as I can tell as it still loads and runs with noe issues

Hopefully that helps narrow it down; this is more of an irritation than a major issue for me, but could be more of hassle to less well-informed users who may assume the addon is completely broken and rage uninstall

**Comment by M-Reimer** [comment] 2021-02-12 14:57
Duplicate of #38
This issue is presented by [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1509701) and if it gets to fixing WebExtensions bugs, you can sometimes wait for many years until something gets fixed. :sob: 
I've linked an easier workaround on the addons.mozilla.org page and in the GitHub README.md:
https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session
I know that this issue exists. Every now and then someone runs into this. Unfortunately, to this day, I've never managed to reproduce it. If I ever get the same profile corruption on one of my systems, I could try to catch this case to automatically open a page describing the situation and how to fix it.
Unfortunately writing good Firefox Add-ons is all about creative workarounds to hide silly bugs that should be fixed by Mozilla...

**Closed by M-Reimer** 2021-02-12 14:57 UTC
