### ISSUE TITLE
Single Click to Show Items

### ISSUE THREAD

**Issue by Andrewsuares** [M-Reimer/undoclosetab#84] opened 2020-11-03 13:40 UTC
Hello,

Is it possible to do a left click and show a list of tabs that were closed?

Thanks.

**Comment by M-Reimer** [comment] 2020-11-03 14:18
No as this would make it impossible to have both (one-click restore of last tab and optional list to pick).

BTW: I'm pretty sure GitHub has a search feature :stuck_out_tongue: 

Duplicate of at least #73, #71, #63, #40, #32 and #31

**Closed by M-Reimer** 2020-11-03 14:18 UTC
