### ISSUE TITLE
Doesn't work on Firefox 71.0

### ISSUE THREAD

**Issue by VictoriousRaptor** [M-Reimer/undoclosetab#69] opened 2019-12-29 06:24 UTC
Nothing happens when I click the icon. 
Firfox Ver 71.0
undoclosetab 5.0.0

**Comment by M-Reimer** [comment] 2019-12-29 10:28
It does work on Firefox 71. I just tested a few seconds ago.

So we should try to find out what's wrong on your side.

Please start with opening the "Browser Console" by pressing Ctrl+Shift+J

On the top right corner you find a settings menu in the "Browser Console" window. Open it and check "Show Content Messages".

Now click the "Undo Close Tab" toolbar icon and keep a look at possible error messages in the "Browser Console" log window. If you see one that could match to your clicks, please post a screenshot of this.

**Comment by VictoriousRaptor** [comment] 2019-12-29 15:37
Just tried uninstall & reinstall the extension and still doesn't work.
<img width="774" alt="批注 2019-12-29 232815" src="https://user-images.githubusercontent.com/10308169/71558984-d6c4c400-2a93-11ea-8eb6-16f5732c0aff.png">
The error message above occurs everytime I refresh a page.
<img width="759" alt="批注 2019-12-29 232835" src="https://user-images.githubusercontent.com/10308169/71558999-f360fc00-2a93-11ea-8eba-90cfa8ae9bc2.png">
This is what happens when I click the icon. Seems like my browser is broken?

**Comment by M-Reimer** [comment] 2019-12-29 15:41
Duplicate of https://github.com/M-Reimer/undoclosetab/issues/38
And basically a bug in Firefox. I really would also like to have this fixed, but WebExtensions bugs seem to have pretty low priority for Mozilla. I have filed several bugs and monitor some others. They rarely get updates. Some of them are unchanged for years.

But let's try to fix your installation.

Is it OK if we reset your profile? You would have to bookmark all relevant tabs first so you don't loose anything.

Then go to your Firefox preferences. (Menu --> Preferences).
Directly on the start page, remove the check in the checkbox "Restore previous session".
After doing so, restart Firefox once.
This should reset your session and also "unbreak" the sessions API.

Please report back if this fixes this problem for you.

**Comment by VictoriousRaptor** [comment] 2019-12-29 16:00
I did what you said and it works pretty well now. Thanks!

**Comment by M-Reimer** [comment] 2019-12-29 16:02
Thank you for verifying.

This also means that we now have a (validated) workaround. Time to create some step-by-step instruction with screenshots for this.

**Comment by M-Reimer** [comment] 2019-12-30 14:52
I've created some step-by-step instructions:
https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session

**Closed by M-Reimer** 2019-12-30 14:52 UTC
Labels: duplicate, help wanted
