### ISSUE TITLE
Ability to undo close window

### ISSUE THREAD

**Issue by tbertels** [M-Reimer/undoclosetab#26] opened 2017-12-18 10:16 UTC
While the extension is called "Undo close tab", it would be great if there was an additional submenu with recently closed windows.
This would give it all the features of the similar button of Session Saver.

**Comment by M-Reimer** [comment] 2017-12-18 11:24
I consider this to be a duplicate of #25 
I don't like separate menus and it wouldn't be a nice task to list windows either as windows don't actually have favicons or titles in the new API so I would have to dig for the "active tab" to borrow these required values from there.
My current plan is to *optionally* list tabs of closed windows, too. We'll see how good this works.

**Closed by M-Reimer** 2017-12-18 11:24 UTC
