### ISSUE TITLE
Feature request: An option to switch right an left mouse click

### ISSUE THREAD

**Issue by anubis-genix** [M-Reimer/undoclosetab#73] opened 2020-07-04 18:41 UTC
I'd love to have the list shown with a left mouse click and the last closed tab restored with a right click.

**Comment by M-Reimer** [comment] 2020-07-05 08:24
Duplicate of #71, #63, #31 and probably e few others...

What I can do is limited by what API Mozilla offers for Add-on developers. And to have both (quick restore of last closed tab with just one click and a list to choose from) all that is possible is to use the "click" method for the quick restore and place the list into the context menu.

**Closed by M-Reimer** 2020-07-05 08:24 UTC

**Comment by Andrewsuares** [comment] 2020-11-03 14:20
It would be nice if the user could choose this behavior. Left click to show the list and then another click to choose the tab to restore. The default could be the way it is now. Thanks.

**Comment by M-Reimer** [comment] 2020-11-03 14:25
This is limited by the API defined by Mozilla (and partially by Google as Mozilla bases on the Google Chrome API).

A context menu is a context menu and Mozilla hardwired this to "right mouse button". Nothing an Add-on could change. Sorry but there is nothing I could do about this.

**Comment by Andrewsuares** [comment] 2020-11-03 14:59
This one does it somehow.

https://addons.mozilla.org/en-US/firefox/addon/undo-close-tab-button/

**Comment by M-Reimer** [comment] 2020-11-03 16:52
Trust me, you'll find answers to all your questions in one of the referenced Issue reports.

Note to myself: Set up a "Frequently Asked Questions" page in the project Wiki

Yes, other Add-ons are doing just that. But not with a regular menu but with a popup page which imitates a menu.

Doing it that way makes it technically impossible to have both: One click to restore recently closed tab and one click to get the menu with a list of the last X closed tabs.

Having both in just one Add-on is my "main selling point". Actually I use the "one click restore" way more often than the menu.

**Comment by M-Reimer** [comment] 2020-11-03 17:25
Here we go: 
https://github.com/M-Reimer/undoclosetab/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by Andrewsuares** [comment] 2020-11-03 17:46
> Doing it that way makes it technically impossible to have both: One click to restore recently closed tab and one click to get the menu with a list of the last X closed tabs.

Yes. But I don't see the problem in giving the user an option to choose the behavior. There will be users who may not want the "one click restore".

**Comment by M-Reimer** [comment] 2020-11-03 17:49
What they do (emulate the menu) is not that easy. It requires quite a bit of code just for that. And I already have code built in to get the list of closed tabs arranged properly in the context menu.

I don't see any benefit if I basically copy someone else's code into my Add-on just to "give a choice".

Technically you have the choice already: Just use the Add-on that fits your needs better.

**Comment by Andrewsuares** [comment] 2020-11-03 18:09
I understand that it may be harder to implement. I never implied that you should 'copy someone else's code'. That's your own assumption.

Seems like you don't take user feedback too well.

**Comment by M-Reimer** [comment] 2020-11-03 18:35
I have no problem with user feedback. Actually improvement of any open source project heavily depends on feedback and many features already implemented are not my idea but suggestions by users.

Maybe I can describe the problem better like this: Showing a list of recently closed tabs in an emulated menu inside a popup window is a completely different concept. So much different that it makes no sense to place both into one Add-on.

To keep things simple it should be its own Add-on. And as others already did that, I don't see any reason to do it again.
