### ISSUE TITLE
Hover shows the url of a closed tab

### ISSUE THREAD

**Issue by minshifu** [M-Reimer/undoclosetab#99] opened 2021-08-19 06:36 UTC
Thank you for your great addon which has been very helpful. Could Hover Show Urls function be realized? That is, mouseover a closed tab from the menu would show its url. That would make locating a certain closed tab much easier especially when there are many of them. Thank you and best regards!

![图片](https://user-images.githubusercontent.com/5119952/130019617-429f04ef-46f3-4c19-9f5a-88a6a91b2259.png)

**Comment by M-Reimer** [comment] 2021-08-19 17:42
Duplicate of #13 
Duplicate of #54

**Comment by M-Reimer** [comment] 2021-08-19 17:42
All complaints to: https://bugzilla.mozilla.org/show_bug.cgi?id=1559082
I even went through the trouble of creating a patch which got declined by Mozilla

**Closed by M-Reimer** 2021-08-19 17:42 UTC
