### ISSUE TITLE
Sometimes clicking 2 or 3 times is neccesary to open

### ISSUE THREAD

**Issue by khari3** [M-Reimer/undoclosetab#46] opened 2019-02-10 16:57 UTC
Sometimes clicking 2 or 3 times is necessary on the icon to open the tabs

Using latest version of ff.

**Comment by M-Reimer** [comment] 2019-02-10 17:00
I can't reproduce this. Worked well every time for me, so far. With the first click.

Please open the "Browser console" (Ctrl + Shift + J)

Then clear everything (Little paper bin icon on the top left corner).

Now keep this window open and try to restore some tabs. Do you get any messages in the "Browser Console" window? If so, please post them here.

With the current information, that I have, I would have to close this as "Works for me".

**Comment by khari3** [comment] 2019-02-10 17:12
Didn't get any messages

**Comment by M-Reimer** [comment] 2019-02-10 17:57
Then it currently seems like you are the only one with this problem :stuck_out_tongue: 
I'll leave this one open for now but mark it as "help wanted".

**Comment by khari3** [comment] 2019-03-18 07:47
One more advice i forgot is --

avoid laziness in work

**Comment by M-Reimer** [comment] 2019-05-23 18:18
Closing for now.
I can't reproduce the problem and so far noone else seems to have it.
If someone has additional info, please add here.

**Closed by M-Reimer** 2019-05-23 18:18 UTC
Labels: help wanted
