### ISSUE TITLE
Undo Close Tab button icon doesn't go shade pale when Firefox window is unfocused

### ISSUE THREAD

**Issue by Aleksandra0056** [M-Reimer/undoclosetab#136] opened 2024-08-07 01:18 UTC
The Undo Close Tab button icon doesn't go shade pale when the Firefox window is unfocused, but other icons yes.

My solution is to make the Undo Close Tab follow the behaviour of the icon going shade pale when the Firefox window is unfocused.

Undo Close Tab icon on Focused Firefox window:
![Focused window](https://github.com/user-attachments/assets/69503d8b-58c7-487e-b9c3-e2403ec77381)

Undo Close Tab icon on Unfocused Firefox window:
![Unfocused window](https://github.com/user-attachments/assets/706f8c43-f434-49e0-9cb7-0d901d3201bc)

My theme which is on screenshots is: https://addons.mozilla.org/en-US/firefox/addon/rosa-pink/

**Comment by Aleksandra0056** [comment] 2024-08-07 01:28
This same applies to the Toggle Image Animations extension, but I write it here to avoid bug trackers cluttering

Toggle Image Animations icon of Focused Firefox window:
![Toggle Image Animations focused window](https://github.com/user-attachments/assets/e21e6e67-26aa-435d-b101-8330176f1214)

Toggle Image Animations icon of Unfocused Firefox window:
![Toggle Image Animations unfocused window](https://github.com/user-attachments/assets/bd65fbd5-efa1-4015-93a6-f9c5817afb9c)

**Comment by M-Reimer** [comment] 2024-08-07 05:42
Thanks for reporting. Probably all I can do is handle this as duplicate of https://github.com/M-Reimer/undoclosetab/issues/90 or similar.

What I can do with the icon is VERY limited, unfortunately. In my opinion it is not at all uncommon to try to mimic the Firefox icon style but Mozilla intentionally makes this very difficult.

Probably I could detect the window loosing focus and then replace the icon. But that would just add on top of already way too much workaround code and as far as I see this behavior only exists on Windows. For me Windows is not the primary platform to develop for. I don't even have a Windows system to test with.

**Comment by M-Reimer** [comment] 2024-08-09 14:39
I tried on my work laptop, which is the only location where I still can access Windows. It is a Windows 11 installation.
I tried focusing/unfocusing windows and on Windows 11 nothing "goes shade pale". So it even isn't consistent across the Windows platform. There is absolutely no way for Add-ons to detect this case. Would have to be fixed in the Firefox backend. So if this has priority for you, please report here: https://bugzilla.mozilla.org/home

**Closed as completed by M-Reimer** 2024-08-09 14:39 UTC
