### ISSUE TITLE
Undo tabs in the order they were closed

### ISSUE THREAD

**Issue by khari3** [M-Reimer/undoclosetab#41] opened 2019-01-01 02:31 UTC
It doesn't open tabs in the order they were closed

For e.g say i have closed 3 tabs,now when i undo them it is opening the 2'nd tab or the 3'rd tab at first at not in order.

**Comment by M-Reimer** [comment] 2019-01-02 10:56
Please describe a bit more in detail.
The Addon is supposed to work like the following:
- Let's say you close "Tab1" first. Then you close "Tab2" and at last you closed "Tab3"
- If you now hit the button once, it is supposed to reopen "Tab3" first. Then "Tab2" and finally "Tab1"

So it should work the opposite order how you closed tabs. That's what most people expect and that's also how the Firefox default "Undo close tab" feature works.

**Comment by khari3** [comment] 2019-01-02 11:04
For e.g after i have closed tab1,then tab2 and at last closed tab3
Now if i press the button ,it should open tab1 first,then tab2 and tab3.

Add this as optionally

**Comment by M-Reimer** [comment] 2019-01-02 13:37
This would require rewriting some parts of the code and would add just another config option that (in the end) noone uses.
I could add this if you give one REALLY GOOD reason.
The problem is, that the "history", you will restore from, will go (worst case with the right settings) down to the browser start. So if you close a tab after starting your browser, then surf some time, then close other tabs maybe a hour later, then the tab, you closed over an hour ago will be restored and not the tab you closed recently.
This even covers session restore. If you restore the last browser session, then this also restores the "recently closed" list.
I can really think of no reason why someone wants this "restoring order". So, so far, I think this one will be a "WONTFIX".

**Closed** 2019-01-02 13:40 UTC
Labels: wontfix
