### ISSUE TITLE
Open menu by left click

### ISSUE THREAD

**Issue by CodeAlDente** [M-Reimer/undoclosetab#71] opened 2020-03-29 00:53 UTC
I'd like to see the menu of all closed tabs with a simple left click on them instead of right click. Of course this could be set in the options.

**Comment by M-Reimer** [comment] 2020-03-29 11:25
Duplicate of #31 

The whole point is having both: Restore last one with one click and pick from a list with right click.

Replacing "left click" with a list would completely remove the one click restore which in my opinion is the main feature.

**Closed by M-Reimer** 2020-03-29 11:25 UTC
