### ISSUE TITLE
After each start, the list is empty

### ISSUE THREAD

**Issue by StephanieLabaule** [M-Reimer/undoclosetab#121] opened 2022-12-20 22:12 UTC
Good evening, 

Thank you for your answer on addons.mozilla.org, but, sorry, I don't see how to answer you in the thread. 
So, I continue here.

I don't understand why at each start, the list is empty.
It's works for the current session, but not for the previous session.

However, maybe it has nothing to do with it, Firefox's history is not erased. 

An idea ? 
Something to change in the options?

Thanks.

**Comment by M-Reimer** [comment] 2022-12-21 08:58
> Thank you for your answer on addons.mozilla.org, but, sorry, I don't see how to answer you in the thread.

That's because Mozilla meant this to be purely for a short review. Something like the customer reviews on Amazon but for Add-ons. But many people get this wrong.

> I don't understand why at each start, the list is empty.

It should not be empty in most cases.

Can you please close a few tabs in your current session, then restart Firefox and check again directly after restarting? Now you should have the closed tabs of your last session. If you immediately restart Firefox again, then yes, now your list is empty. But that's a different topic. Maybe we can verify first if the expected behavior (the very last session should still be there) works for you.

If that's not the case, we would have to check if any error messages are logged.

**Comment by StephanieLabaule** [comment] 2022-12-21 09:57
Hello,

Thank you for answering.

I confirm that it is indeed the tabs closed in the previous session that do not appear.
Where can I see error messages?

Thank you.

**Comment by StephanieLabaule** [comment] 2022-12-21 10:37
Alright, I think I have a lead.

I also use "Tab Session Manager". And I notice that on startup it opens an empty window and then closes it to open a new one with the previous session. I don't know if this is how it works normally, but by disabling "Tab Session Manager", "Undo Close Tab" again works as you indicate.

So I will look on the side of "Tab Session Manager".

Thanks for the help, and sorry for the inconvenience.

**Comment by M-Reimer** [comment] 2022-12-21 10:52
No problem.

Yes, there could be some conflict between Add-ons. And what I'm doing is more a hack which probably can never work well with other Add-ons (like "Tab Session Manager"). So probably you have to choose what you like best and only use one of the two Add-ons. As Firefox already has a "closed tab history". Probably your best choice would be to uninstall "Undo Close Tab".

The root problem here is that the Add-on API is broken (for years). The "only up to the last session" part is covered in Issue #79 which basically depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1538119
And I also reported this earlier to Mozilla in this bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1408575 which I closed myself in favor of the other bug which has better description and a test case.

To describe the issue in very short terms: Mozilla has an internal "counter" which is counted up with every closed tab. The "counter value" is now the "identifier" for this closed tab so Add-ons can reference to it for getting them restored. If you close the browser, then all the closed tabs and their identifiers are saved for restoring. The issue is now that, if you open a new session, Mozilla "resets" this counter and starts counting from 1 again which basically means that "identifiers" are now duplicated while you close new tabs. One identifier now points to two possible tabs for restoring and it is random which one you get restored.

I "fixed" this with a pretty silly workaround. This workaround very likely causes issues in your case. So it also does not make much sense to ask the developer of "Tab Session Manager" for a fix.

This has to be fixed by Mozilla. But unfortunately this is not the only bug that is sitting there for years without getting too much attention. In my opinion Mozilla really lacks manpower for maintaining their backend code. And Add-ons and their API is really, really, REALLY, low priority for Mozilla.

**Comment by StephanieLabaule** [comment] 2022-12-21 20:30
Thank you very much for all these explanations.

**Closed** 2023-05-07 18:00 UTC
