### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by 532910** [M-Reimer/undoclosetab#64] opened 2019-08-25 23:46 UTC
Version 4.7.0
firefox 68.0.2-3
debian sid

**Comment by M-Reimer** [comment] 2019-08-26 04:38
More details please. With the amount of details you gave I can just close this one as "works for me".

**Comment by 532910** [comment] 2019-08-26 11:34
It just doesn't work, and I have no details more unfortunately.
Could  you help me to debug this issue? I can provide any details you ask.

**Comment by M-Reimer** [comment] 2019-08-26 12:08
The very first thing to test is a new profile. Please Google for Firefox profile manager to create a fresh profile next to your current one.

**Comment by 532910** [comment] 2019-08-26 12:17
It works with a new profile.

**Comment by M-Reimer** [comment] 2019-08-26 14:51
So this is a duplicate of #38

So far noone really did the "hard work" to pinpoint the issue, but maybe you have the time to do so.

At first: Do you use "Firefox sync"? I don't so this may be the reason why I never ran into this issue.

Neither me nor Mozilla actually know where the problem comes from but I think it would help to solve the issue (and to fix corrupted profiles) if we knew which file is causing this.

You can delete nearly every file in the Firefox profile without negative effect. Firefox will just recreate the file at the next start.

So please create a backup copy of the problematic profile. Then be sure that Firefox is closed and start by deleting **one** file at a time. Just follow your intuition. After every file delete, open Firefox with this profile and check if the problem is solved. Then close Firefox before deleting the next file.

If you think you found a file where deleting fixes the problem, then restore the backup and delete only this file (to be sure that the other recreated files have no effect).

After the test, tell me which file has to be deleted to fix the problem.

Would really help me, all the users who run into this problem and probably even Mozilla with fixing https://bugzilla.mozilla.org/show_bug.cgi?id=1509701

**Comment by 532910** [comment] 2019-08-26 20:29
> Do you use "Firefox sync"?

yes

OK, if you are sure this is due to some corrupted file, I'll find it.

**Comment by 532910** [comment] 2019-08-26 21:07
From the first attempt: `rm -rf sessionstore.jsonlz4 sessionstore-backups`

**Comment by M-Reimer** [comment] 2019-08-26 21:13
Great start! :+1: 
Can this be limited even further? I guess the backups don't have to go, so maybe it's only "sessionstore.jsonlz4"

**Comment by 532910** [comment] 2019-08-26 21:22
No, if I remove the only `sessionstore.jsonlz4` it restores session from backup automatically.

**Comment by M-Reimer** [comment] 2019-08-27 08:06
Makes sense. Thanks for finding the problematic file. This makes it possible to revive profiles with this problem. I'm wondering why Firefox itself doesn't seem to have any problem with the "broken" session file but the WebExtensions API fails.

**Comment by M-Reimer** [comment] 2019-08-27 18:10
I'll create a markdown page describing how to fix a broken profile. Then I'll link to this from the GitHub README.md and from addons.mozilla.org in hope that affected people find this.

In theory it may be possible to catch this error and automatically open a tab with instructions on how to fix this problem. But for properly creating this, I would have to reproduce this on one of my systems.

As I think this is triggered by Firefox Sync somehow, I'll configure one of my systems to use Sync. Maybe this helps to reproduce this eventually.

**Comment by 532910** [comment] 2019-08-31 17:09
Now it works for me!

**Comment by nollinvoyd** [comment] 2019-09-09 20:28
I'd like to relate my experience with this problem.

When I installed undo close tab on a new profile I was in the process of building, that already had a few tabs collected and a bit of history, undo close tab did not work.  In fact, even the context menu options didn't work.  The button showed up on the toolbar, but that was it.

Then I tested it on a completely fresh profile, and it worked.

I went about the task of finding out why.  After trial and error, I found If I deleted all the session related files, places file, and cookie files, undo close tab would work.  But it did not seem reasonable that I would have to give up all my sessions, history, and protected cookies to use undo close tab.

I decided to replace those files I previously mentioned with those from an older working profile to the new one, and undo close tab is now working properly.  

In my case, if there was any file "corruption", I have to believe the installation of undo close tab had something to do with it.

Your the expert.  I may be wrong, but that's my theory.

**Comment by M-Reimer** [comment] 2019-09-09 21:34
It is a bug in the Mozilla API.
I think the corruption happened before installing. Maybe Firefox sync triggers this somehow. You don't see the problem in normal use but the code which serves the API misbehaves with the corrupted session file. Mozilla has to fix this somehow.
Problem is that fixing API related stuff seems to be lowest priority. Even if you have a patch ready noone answers 😟

**Comment by nollinvoyd** [comment] 2019-09-09 22:03
Thanks for responding.  I want to continue using, so for now, I hope no other damage will have to be dealt with beyond my workaround.  So far, so good.

FWIW, I'm not using sync, so that's not a factor.

**Comment by j-degreef** [comment] 2019-09-10 20:05
No solution exists without loosing the profile you're using.
Firefox once again sucks major asses. They redo their extension api and since it's a catastrophe. 
Plus FF 69 breaks things that were working with previous versions ea this extensions.

Sad to see the best browser taking the wrong way, they're doing their best to lead users to Chrome ?!?

**Comment by 532910** [comment] 2019-09-10 21:50
It started working accidentally for me without removing session files.

**Comment by M-Reimer** [comment] 2019-09-11 05:51
So deleting these files didn't help or did you keep using the "bad" files and they went "good" somehow?

**Comment by 532910** [comment] 2019-09-11 06:16
The second one, "bad" files went "good" somehow.

**Comment by M-Reimer** [comment] 2019-09-11 18:10
Forwarded the latest findings to Mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1509701#c1

I'll keep this one open as a reminder that I still have to create some step-by-step instructions on how to delete the problematic files.

What would actually happen if I delete the session files and I am using Firefox Sync? Will Sync recreate my tabs in this case?

**Comment by nollinvoyd** [comment] 2019-09-11 23:50
I don't know if it will work, but try this.  Backup your profile.  Uninstall undo closed tab.  Go the the profile and backup all the files I mentioned above, reinstall undo closed tab, close the browser, replace the newly created files with the ones you backed up, restart the browser and see what happens.

**Comment by 532910** [comment] 2019-09-12 01:39
> What would actually happen if I delete the session files and I am using Firefox Sync? Will Sync recreate my tabs in this case?

No, you'll loose your session.

**Comment by M-Reimer** [comment] 2019-09-15 09:35
There may be an even easier way to workaround this but I didn't test.
Maybe someone can try this.

- Go to your Firefox preferences (about:preferences)
- Uncheck "Restore previous session" right at the top
- Restart Firefox

Should also result in a fresh session to start with. Recheck "Restore previous session" if you like.

**Comment by M-Reimer** [comment] 2019-12-30 14:53
I've created some step-by-step instructions:
https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session

**Closed by M-Reimer** 2019-12-30 14:53 UTC
Labels: duplicate, help wanted
