### ISSUE TITLE
List of recently closed tabs missing from right click menu

### ISSUE THREAD

**Issue by gaiaweylyn** [M-Reimer/undoclosetab#119] opened 2022-10-12 23:22 UTC
On the latest Firefox update (Running 105.0.2 on Windows 10 as of issue posting), I can no longer right click directly on the Undo Close Tab toolbar icon to click and reopen individual recently closed tabs. Instead of showing the list, it just shows the generic Manage/Remove/Report/etc context menu items. 

This can still be done manually through several clicks into the stock Firefox History menus, but having that right on the Undo Close Tab button was a massive convenience plus.

**Comment by M-Reimer** [comment] 2022-10-13 04:37
Sorry but this is a duplicate of #117. And I currently am no longer able to reproduce this issue.

**Closed by M-Reimer** 2022-10-13 04:37 UTC
